# generated by datamodel-codegen:
#   filename:  CSI-005-001_ChainManager.yml
#   timestamp: 2023-05-25T22:26:32+00:00

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


class LinkReceiveReady(Enum):
    RECEIVE_READY = 'RECEIVE_READY'
    RECEIVE_NOT_READY = 'RECEIVE_NOT_READY'


class LinkReceiveLocked(Enum):
    LOCKED = 'LOCKED'
    NOT_LOCKED = 'NOT_LOCKED'


class LinkReceivingData(Enum):
    RECEIVING_DATA = 'RECEIVING_DATA'
    NOT_RECIVING_DATA = 'NOT_RECIVING_DATA'


class LinkTransmitReady(Enum):
    TRANSMIT_READY = 'TRANSMIT_READY'
    TRANSMIT_NOT_READY = 'TRANSMIT_NOT_READY'


class LinkTransmittingData(Enum):
    TRANSMITTING_DATA = 'TRANSMITTING_DATA'
    NOT_TRANSMITTING_DATA = 'NOT_TRANSMITTING_DATA'


class ParametersStopTransmit(Enum):
    SAFE_STOP = 'SAFE_STOP'
    EMERGENCY_STOP = 'EMERGENCY_STOP'


class ChainManagerYml(BaseModel):
    field_version_function: Optional[str] = Field(
        None,
        description='“chain-2021.12.22” for this version, which specifies the fields in this table.',
        title='field_version_function',
    )
    link_receive_ready: Optional[LinkReceiveReady] = Field(
        None,
        alias='link.receive_ready',
        description='Indicates if the endpoint is configured to receive.',
        title='receive_ready',
    )
    link_receive_locked: Optional[LinkReceiveLocked] = Field(
        None,
        alias='link.receive_locked',
        description='Indicates if the endpoint is locked to the carrier.',
        title='receive_locked',
    )
    link_receiving_data: Optional[LinkReceivingData] = Field(
        None,
        alias='link.receiving_data',
        description='Indicates if the endpoint is receiving the carrier.',
        title='receiving_data',
    )
    link_transmit_ready: Optional[LinkTransmitReady] = Field(
        None,
        alias='link.transmit_ready',
        description='Indicates if the endpoint is configured to transmit.',
        title='transmit_ready',
    )
    link_transmitting_data: Optional[LinkTransmittingData] = Field(
        None,
        alias='link.transmitting_data',
        description='Indicates if the endpoint is actively transmitting data.',
        title='transmitting_data',
    )
    parameters_receive_ota_frequency_hz: Optional[float] = Field(
        None,
        alias='parameters.receive_ota_frequency_hz',
        description='Over-the-air center frequency to which the system is tuned for receive that accounts for all stages of conversion (channelizers, BDCs, IF, etc.).',
        title='receive_ota_frequency_hz',
    )
    parameters_search_frequency_ota_min_hz: Optional[float] = Field(
        None,
        alias='parameters.search_frequency_ota_min_hz',
        description='Allows the modem to account for error in the center frequency setting by allowing the modem to search within a specified range to find the actual center frequency. This setting is the minimum allowable value to lock onto and be able to assume it is the correct signal.',
        title='search_frequency_ota_min_hz',
    )
    parameters_search_frequency_ota_max_hz: Optional[float] = Field(
        None,
        alias='parameters.search_frequency_ota_max_hz',
        description='Allows the modem to account for error in the center frequency setting by allowing the modem to search within a specified range to find the actual center frequency. This setting is the maximum allowable value to lock onto and be able to assume it is the correct signal.',
        title='search_frequency_ota_max_hz',
    )
    parameters_receive_gain_db: Optional[float] = Field(
        None,
        alias='parameters.receive_gain_db',
        description='Aggregate of all gain stages in the system. Allows the system to optimally adjust gain stages in the receive chain.',
        title='receive_gain_db',
    )
    parameters_transmit_ota_frequency_hz: Optional[float] = Field(
        None,
        alias='parameters.transmit_ota_frequency_hz',
        description='Over-the-air center frequency to which the system is tuned for transmit that accounts for all stages of conversion (channelizers, BUCs, IF, etc.).',
        title='transmit_ota_frequency_hz',
    )
    parameters_transmit_power_dBm: Optional[float] = Field(
        None,
        alias='parameters.transmit_power_dBm',
        description='Output power going out of the antenna that includes all gain stages (including antenna gain). Allows the system to optimally adjust gain stages in the transmit chain.',
        title='transmit_power_dBm',
    )
    parameters_stop_transmit: Optional[ParametersStopTransmit] = Field(
        None,
        alias='parameters.stop_transmit',
        description='Forces the endpoint to stop transmitting. SAFE_STOP-Stops transmitting gracefully. EMERGENCY_STOP- Stops transmitting immediately.',
        title='stop_transmit',
    )
