# generated by datamodel-codegen:
#   filename:  CSI-002-022_Antenna.yml
#   timestamp: 2023-05-25T22:20:48+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class Antenna(BaseModel):
    parameters_reflector_size_m: Optional[float] = Field(
        None,
        alias='parameters.reflector_size_m',
        description='Diameter of the reflector.',
        title='reflector_size_m',
    )
    parameters_gain_dBi: Optional[float] = Field(
        None, alias='parameters.gain_dBi', description='Midband gain.', title='gain_dBi'
    )
    parameters_beam_width_degrees: Optional[float] = Field(
        None,
        alias='parameters.beam_width_degrees',
        description='The 3dB beam width.',
        title='beam_width_degrees',
    )
    parameters_max_power_dBm: Optional[float] = Field(
        None,
        alias='parameters.max_power_dBm',
        description='Maximum power input that the antenna is rated to handle.',
        title='max_power_dBm',
    )
