# generated by datamodel-codegen:
#   filename:  CSI-002-001_AntennaControlSystem.yml
#   timestamp: 2023-05-25T22:06:48+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field


class Stow(Enum):
    STOW_HORIZONTAL = 'STOW_HORIZONTAL'
    STOW_VERTICAL = 'STOW_VERTICAL'


class StowState(Enum):
    UNKNOWN = 'UNKNOWN'
    NOT_STOWED = 'NOT_STOWED'
    MOVING_TO_STOW = 'MOVING_TO_STOW'
    STOWED_HORIZONTAL = 'STOWED_HORIZONTAL'
    STOWED_VERTICAL = 'STOWED_VERTICAL'


class Polarity(Enum):
    LINEAR_HORIZONTAL = 'LINEAR_HORIZONTAL'
    LINEAR_VERTICAL = 'LINEAR_VERTICAL'
    CIRCULAR_LEFT = 'CIRCULAR_LEFT'
    CIRCULAR_RIGHT = 'CIRCULAR_RIGHT'


class AntennaControl(BaseModel):
    stow: Optional[Stow] = Field(
        None,
        description='control the antenna to either go to stow or active mode.',
        title='stow',
    )
    stow_state: Optional[StowState] = Field(
        None, description='Gets the current state of stow control.', title='stow_state'
    )
    polarity: Optional[Polarity] = Field(
        None, description='Polarity of the antenna.', title='polarity'
    )
    polarity_angle_degrees: Optional[float] = Field(
        None,
        description='For linear polarization, offset in degrees from the selected polarity.',
        title='polarity_angle_degrees',
    )
    elevation_point_degrees: Optional[float] = Field(
        None,
        description='This is the actual pointing angle of that is specified by antenna pointing calculators and is independent of the dish offset angle.',
        title='elevation_point_degrees',
    )
    elevation_offset_degrees: Optional[float] = Field(
        None,
        description='This is the elevation offset angle that is dictated by the antenna design.',
        title='elevation_offset_degrees',
    )
    azimuth_angle_degrees: Optional[float] = Field(
        None,
        description='Angle antenna is pointed relative to true north in a clockwise direction.',
        title='azimuth_angle_degrees',
    )
    selected_tle_name: Optional[str] = Field(
        None,
        description='Name of the two-line element that is currently selected for tracking the satellite.',
        title='selected_tle_name',
    )
    tle_names: Optional[List[str]] = Field(
        None,
        description='List of names for TLE files stored on the system.',
        title='tle_names',
    )
    delete_tle_file: Optional[str] = Field(
        None,
        description='Deletes the TLE file with the specified file name.',
        title='delete_tle_file',
    )
    get_tle_file: Optional[str] = Field(
        None,
        description='Informs the ACS proxy when there is a TLE file available on the endpoint File Manager as described in CSI-000-009 File Transfer.',
        title='get_tle_file',
    )
