# generated by datamodel-codegen:
#   filename:  CSI-002-002_BlockDownconverter.yml
#   timestamp: 2023-05-25T22:06:52+00:00

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


class AgcEnabled(Enum):
    ENABLED = 'ENABLED'
    DISABLED = 'DISABLED'


class SpectralInversion(Enum):
    INVERTED = 'INVERTED'
    NOT_INVERTED = 'NOT_INVERTED'


class BlockDownConverter(BaseModel):
    field_version_function: Optional[str] = Field(
        None,
        description='“bdc-2022.03.07” for this version, which specifies the fields in this table.',
        title='field_version_function',
    )
    agc_enabled: Optional[AgcEnabled] = Field(
        None,
        description='Commands the antenna to go into a stowed state for teardown or to Automatic gain control status.',
        title='agc_enabled',
    )
    gain_db: Optional[float] = Field(
        None, description='Gain setting of the block downconverter.', title='gain_db'
    )
    conversion_frequency_hz: Optional[float] = Field(
        None,
        description='Frequency of the local oscillator used to downconvert from the over-the-air frequency to intermediate frequencies.',
        title='conversion_frequency_hz',
    )
    spectral_inversion: Optional[SpectralInversion] = Field(
        None,
        description='Indicates if the spectrum is inverted during the process of converting from the over-the-air frequency to IF frequency.',
        title='spectral_inversion',
    )
