# generated by datamodel-codegen:
#   filename:  CSI-002-003_BlockUpconverter.yml
#   timestamp: 2023-05-25T22:07:20+00:00

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


class AgcEnabled(Enum):
    ENABLED = 'ENABLED'
    DISABLED = 'DISABLED'


class SpectralInversion(Enum):
    INVERTED = 'INVERTED'
    NOT_INVERTED = 'NOT_INVERTED'


class BlockUpConverter(BaseModel):
    field_version_function: Optional[str] = Field(
        None,
        description='“buc-2022.03.07” for this version, which specifies the fields in this table.',
        title='field_version_function',
    )
    agc_enabled: Optional[AgcEnabled] = Field(
        None, description='Automatic gain control status.', title='agc_enabled'
    )
    gain_db: Optional[float] = Field(
        None, description='Gain setting of the block upconverter.', title='gain_db'
    )
    conversion_frequency_hz: Optional[float] = Field(
        None,
        description='Frequency of the local oscillator used to upconvert from the intermediate frequencies',
        title='conversion_frequency_hz',
    )
    spectral_inversion: Optional[SpectralInversion] = Field(
        None,
        description='Indicates if the spectrum is inverted during the process of converting from the IF frequency to over-the-air frequency.',
        title='spectral_inversion',
    )
