# generated by datamodel-codegen:
#   filename:  CSI-002-019_DataStorage.yml
#   timestamp: 2023-05-25T22:14:08+00:00

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


class ParametersClear(Enum):
    CLEAR = 'CLEAR'


class DataStorage(BaseModel):
    parameters_files: Optional[str] = Field(
        None,
        alias='parameters.files',
        description='Returns a list of all files and directories on the data store.',
        title='parameters.files',
    )
    parameters_clear: Optional[ParametersClear] = Field(
        None,
        alias='parameters.clear',
        description='CLEAR- Wipes all stored data.',
        title='parameters.clear',
    )
    parameters_remove_file: Optional[str] = Field(
        None,
        alias='parameters.remove_file',
        description='Specifies a file to remove.',
        title='parameters.remove_file',
    )
    parameters_remove_directory: Optional[str] = Field(
        None,
        alias='parameters.remove_directory',
        description='Specifies a directory to remove, to include all subdirectories.',
        title='parameters.remove_directory',
    )
    sensors_storage_total_mbytes: Optional[float] = Field(
        None,
        alias='sensors.storage_total_mbytes',
        description='Total number of megabytes available for storing data.',
        title='sensors.storage_total_mbytes',
    )
    sensors_storage_used_mbytes: Optional[float] = Field(
        None,
        alias='sensors.storage_used_mbytes',
        description='Total number of megabytes used on the data store.',
        title='sensors.storage_used_mbytes',
    )
