# generated by datamodel-codegen:
#   filename:  CSI-002-017_EnvironmentSensor.yml
#   timestamp: 2023-05-25T22:12:02+00:00

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


class ParametersResetHistory(Enum):
    RESET = 'RESET'


class SensorsContactClosure(Enum):
    OPEN = 'OPEN'
    CLOSED = 'CLOSED'


class SensorsMotion(Enum):
    MOTION = 'MOTION'
    NO_MOTION = 'NO_MOTION'


class EnvironmentSensor(BaseModel):
    parameters_reset_history: Optional[ParametersResetHistory] = Field(
        None,
        alias='parameters.reset_history',
        description='Resets all averages, max holds, etc. for all sensors.',
        title='parameters.reset_history',
    )
    sensors_humidity_percent: Optional[float] = Field(
        None,
        alias='sensors.humidity_percent',
        description='Measures humidity.',
        title='sensors.humidity_percent',
    )
    sensors_wind_average_kmph: Optional[float] = Field(
        None,
        alias='sensors.wind_average_kmph',
        description='Short-term average wind speed with the duration of average determined by the proxy.',
        title='sensors.wind_average_kmph',
    )
    sensors_wind_peak_kmph: Optional[float] = Field(
        None,
        alias='sensors.wind_peak_kmph',
        description='Peak wind speed measurement.',
        title='sensors.wind_peak_kmph',
    )
    sensors_airflow_mps: Optional[float] = Field(
        None,
        alias='sensors.airflow_mps',
        description='Airflow measurement (usually for indoor components).',
        title='sensors.airflow_mps',
    )
    sensors_contact_closure: Optional[SensorsContactClosure] = Field(
        None,
        alias='sensors.contact_closure',
        description='General purpose sensors that read open/closed. OPEN- sensor is in open state, CLOSED- sensor is in closed state.',
        title='sensors.contact_closure',
    )
    sensors_pressure_pa: Optional[float] = Field(
        None,
        alias='sensors.pressure_pa',
        description='Measured value of pressure.',
        title='sensors.pressure_pa',
    )
    sensors_water_depth_m: Optional[float] = Field(
        None,
        alias='sensors.water_depth_m',
        description='Measured water depth.',
        title='sensors.water_depth_m',
    )
    sensors_vibration_g: Optional[float] = Field(
        None,
        alias='sensors.vibration_g',
        description='Measured vibration.',
        title='sensors.vibration_g',
    )
    sensors_motion: Optional[SensorsMotion] = Field(
        None,
        alias='sensors.motion',
        description='Motion detection.',
        title='sensors.motion',
    )
