# generated by datamodel-codegen:
#   filename:  CSI-002-006_GainBlock.yml
#   timestamp: 2023-05-25T22:08:19+00:00

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


class AgcEnabled(Enum):
    ENABLED = 'ENABLED'
    DISABLED = 'DISABLED'


class GainBlock(BaseModel):
    field_version_function: Optional[str] = Field(
        None,
        description='“gain-2021.12.20” for this version, which specifies the fields in this table.',
        title='field_version_function',
    )
    agc_enabled: Optional[AgcEnabled] = Field(
        None, description='Automatic gain control status.', title='agc_enabled'
    )
    gain_dB: Optional[float] = Field(
        None, description='Gain setting of the amplifier.', title='gain_dB'
    )
    rssi_dBm: Optional[float] = Field(
        None, description='Received Signal Strength Input.', title='rssi_dBm'
    )
