# generated by datamodel-codegen:
#   filename:  CSI-002-023_Gps.yml
#   timestamp: 2023-05-25T22:21:12+00:00

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


class ParametersLockStatus(Enum):
    LOCKED = 'LOCKED'
    LOCKING = 'LOCKING'
    LOCK_FAULT = 'LOCK_FAULT'
    ANTENNA_FAULT = 'ANTENNA_FAULT'


class ParametersRetryLock(Enum):
    RETRY = 'RETRY'


class Gps(BaseModel):
    parameters_lock_status: Optional[ParametersLockStatus] = Field(
        None,
        alias='parameters.lock_status',
        description='LOCKED- GPS locked, LOCKING- Attempting to lock, LOCK_FAULT- Unable to lock, ANTENNA-FAULT- Antenna not responding/ not connected',
        title='lock_status',
    )
    parameters_retry_lock: Optional[ParametersRetryLock] = Field(
        None, alias='parameters.retry_lock', description='RETRY', title='retry_lock'
    )
    parameters_lock_timeout_seconds: Optional[float] = Field(
        None,
        alias='parameters.lock_timeout_seconds',
        description='Amount of time to search for GPS signal before a lock failure fault is generated.',
        title='lock_timeout_seconds',
    )
    parameters_current_zulu_time: Optional[str] = Field(
        None,
        alias='parameters.current_zulu_time',
        description='Gets current zulu time form the GPS module.',
        title='current_zulu_time',
    )
    parameters_current_local_time: Optional[str] = Field(
        None,
        alias='parameters.current_local_time',
        description='Gets current local time at the endpoint.',
        title='current_local_time',
    )
