# generated by datamodel-codegen:
#   filename:  CSI-002-005_HighPowerAmplifier.yml
#   timestamp: 2023-05-25T22:07:50+00:00

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


class RfEnabled(Enum):
    ENABLED = 'ENABLED'
    SUPRESSED = 'SUPRESSED'


class SpectralInversion(Enum):
    INVERTED = 'INVERTED'
    NOT_INVERTED = 'NOT_INVERTED'


class HighPowerAmplifier(BaseModel):
    rf_enabled: Optional[RfEnabled] = Field(
        None,
        description='Current state of RF output, ENABLED-The HPA is transmitting into the antenna dummy load. SUPPRESSED- The HPA output is suppressed and not transmitting into the antenna dummy load.',
        title='rf_enabled',
    )
    output_power_dbm: Optional[float] = Field(
        None,
        description='Expected output power from the HPA into the antenna dummy load.',
        title='output_power_dbm',
    )
    gain_db: Optional[float] = Field(
        None, description='Gain added to the signal by the HPA.', title='gain_db'
    )
    attenuation_db: Optional[float] = Field(
        None,
        description='Attenuation applied to the signal by the HPA.',
        title='attenuation_db',
    )
    conversion_frequency_hz: Optional[float] = Field(
        None,
        description='For HPAs with integrated BUC, this is the local oscillator frequency used to convert the IF input to the HPA to the over-the-air frequency.',
        title='conversion_frequency_hz',
    )
    spectral_inversion: Optional[SpectralInversion] = Field(
        None,
        description='Indicates if the spectrum is inverted during the process of converting from IF frequency to over the air frequency.',
        title='spectral_inversion',
    )
    powerIn_dBm: Optional[float] = Field(
        None, description='Measured power at the input to the HPA.', title='powerIn_dBm'
    )
    powerOut_dBm: Optional[float] = Field(
        None,
        description='Measured power at the output of the HPA.',
        title='powerOut_dBm',
    )
    powerDraw_W: Optional[float] = Field(None, title='powerDraw_W')
