# generated by datamodel-codegen:
#   filename:  CSI-002-018_RfFiberRfConverter.yml
#   timestamp: 2023-05-25T22:12:29+00:00

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


class AgcEnabled(Enum):
    ENABLES = 'ENABLES'
    DISABLED = 'DISABLED'


class RfFiberRfConverter(BaseModel):
    agc_enabled: Optional[AgcEnabled] = Field(
        None,
        description='Indicates if automatic gain control is enabled.',
        title='agc_enabled',
    )
    gain_dB: Optional[float] = Field(
        None, description='Current gain setting of the converter.', title='gain_dB'
    )
