# generated by datamodel-codegen:
#   filename:  CSI-002-013_SdrReceive.yml
#   timestamp: 2023-05-25T22:09:00+00:00

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


class ModemType(Enum):
    ACM = 'ACM'
    CinC = 'CinC'
    DVB_S = 'DVB-S'
    DVB_S2 = 'DVB-S2'
    DVB_S2X = 'DVB-S2X'
    MCPT = 'MCPT'
    SCPC = 'SCPC'
    SCPT_L = 'SCPT-L'
    SCPT_NL = 'SCPT-NL'


class SpectralInversion(Enum):
    INVERTED = 'INVERTED'
    NOT_INVERTED = 'NOT_INVERTED'


class FilterRolloff(Enum):
    field_0_05 = 0.05
    field_0_1 = 0.1
    field_0_15 = 0.15
    field_0_2 = 0.2
    field_0_25 = 0.25
    field_0_35 = 0.35


class Modulation(Enum):
    FSK = 'FSK'
    BPSK = 'BPSK'
    QPSK = 'QPSK'
    OQPSK = 'OQPSK'
    field_8APSK_L = '8APSK-L'
    field_8PSK = '8PSK'
    field_8QAM = '8QAM'
    field_16APSK = '16APSK'
    field_16APSK_L = '16APSK-L'
    field_16QAM = '16QAM'
    field_32APSK = '32APSK'
    field_32APSK_L = '32APSK-L'
    field_64APSK = '64APSK'
    field_64APSK_L = '64APSK-L'
    field_128APSK = '128APSK'
    field_256APSK = '256APSK'
    field_256APSK_L = '256APSK-L'


class FecOuter(Enum):
    BCH = 'BCH'
    HAMMING = 'HAMMING'
    LDPC = 'LDPC'
    PROPRIETARY = 'PROPRIETARY'
    RS = 'RS'
    SEQUENTIAL = 'SEQUENTIAL'
    TCM = 'TCM'
    TPC = 'TPC'
    VITERBI = 'VITERBI'


class Scrambling(Enum):
    V_35 = 'V.35'
    PROPRIETARY = 'PROPRIETARY'


class Framing(Enum):
    DVB_S2_BB = 'DVB-S2 BB'
    DVB_ASI = 'DVB-ASI'
    GSE = 'GSE'
    HDLC = 'HDLC'
    MPEG_2 = 'MPEG-2'
    PROPRIETARY = 'PROPRIETARY'


class ReceiveLock(Enum):
    LOCKED = 'LOCKED'
    NOT_LOCKED = 'NOT_LOCKED'


class ModemReceive(BaseModel):
    field_version_function: Optional[str] = Field(
        None,
        description='“modem_receive-2022.03.07” for this version, which specifies the fields in this table.',
        title='field_version_function',
    )
    modem_type: Optional[ModemType] = Field(
        None,
        description='Enumeration that defines the type of modem ACM- Adaptive Coding and Modulation CinC- Carrier-in-Carrier where two signals utilize the same bandwidth DVB-S- Digital Video Broadcast over Satellite DVB-S2- Digital Video Broadcast over Satellite version 2 DVB-S2X- Digital Video Broadcast over Satellite version 2 with extenstions MCPT- Multiple Carrier per Transponder SCPC- Single Carrier per Channel SCPT-L- Single Carrier Per Transponder - Linear SCPT-NL- Single Carrier Per Transponder - Non Linear',
        title='modem_type',
    )
    gain_db: Optional[float] = Field(
        None, description='Gain applied to the receive path.', title='gain_db'
    )
    spectral_inversion: Optional[SpectralInversion] = Field(
        None,
        description='If INVERTED, invert the spectrum before processing in the receiver. INVERTED- The input to the receiver is inverted. NOT_INVERTED- The input to the receiver is not inverted.',
        title='spectral_inversion',
    )
    center_frequency_hz: Optional[float] = Field(
        None,
        description='Modem intermediate frequency. Typically, in 70 MHz, 140 MHz, or L (950-2150 MHz) band.',
        title='center_frequency_hz',
    )
    search_frequency_min_hz: Optional[float] = Field(
        None,
        description='Allows the modem to account for error in the center frequency setting by allowing the modem to search within a specified range to find the actual center frequency.This setting is the minimum allowable value to lock onto and be able to assume it is the correct signal.',
        title='search_frequency_min_hz',
    )
    search_frequency_max_hz: Optional[float] = Field(
        None,
        description='Allows the modem to account for error in the center frequency setting by allowing the modem to search within a specified range to find the actual center frequency.This setting is the maximum allowable value to lock onto and be able to assume it is the correct signal.',
        title='search_frequency_max_hz',
    )
    filter_rolloff: Optional[FilterRolloff] = Field(
        None,
        description='Squared-root raised cosine filter rolloff.0.05, 0.10, 0.15, 0.20, 0.25, 0.35',
        title='filter_rolloff',
    )
    modulation: Optional[Modulation] = Field(
        None, description='Selected modulation.', title='modulation'
    )
    symbol_rate_ksps: Optional[float] = Field(
        None,
        description='Symbol rate of the selected modulation in kilo symbols per second',
        title='symbol_rate_ksps',
    )
    fec_outer: Optional[FecOuter] = Field(
        None,
        description='Selected outer layer FEC BCH- Bose–Chaudhuri–Hocquenghem, HAMMING, LDPC- Low Density Parity Check, PROPRIETARY- Proprietary format not listed, RS- Reed-Solomon, SEQUENTIAL, TCM- Trellis Coded Modulation- TPC Turbo Product Code, VITERBI',
        title='fec_outer',
    )
    fec_outer_rate: Optional[str] = Field(
        None,
        description='Rate for the outer FEC. This field must support typical and atypical rates.Typical rates:1/4, 1/3, 2/5, 1/2, 3/5, 2/3, 3/4, 4/5, 5/6, 7/8, 8/9, 9/10',
        title='fec_outer_rate',
    )
    fec_inner: Optional[str] = Field(
        None,
        description='Not used with a single layer FEC. When applicable, same options as fec_outer.',
        title='fec_inner',
    )
    fec_inner_rate: Optional[str] = Field(
        None,
        description='Not used with a single layer FEC. When applicable, same options as fec_outer_rate',
        title='fec_inner_rate',
    )
    scrambling: Optional[Scrambling] = Field(
        None,
        description='Bit scrambler, V.35- https://www.itu.int/rec/T-REC-V.35-198410-W/en, PROPRIETARY- Proprietary format not listed.',
        title='scrambling',
    )
    framing: Optional[Framing] = Field(
        None,
        description='Data framing, BB Frame- Base Band Frame, DVB ASI- Asynchronous Serial Interface, GSE- Generic Stream Encapsulation, HDLC- High-Level Data Link Control, MPEG-2- MPEG Layer 2 Control, PROPRIETARY- roprietary format not listed.',
        title='framing',
    )
    rssi_dBm: Optional[float] = Field(
        None,
        description='Received signal strength at the input to the modem',
        title='rssi_dBm',
    )
    receive_lock: Optional[ReceiveLock] = Field(
        None,
        description='Indicates whether the receiver is in the locked state.',
        title='receive_lock',
    )
    receive_start_time: Optional[str] = Field(
        None,
        description='If the receiver is currently locked, this is the timestamp when the modem first achieved lock on the carrier.',
        title='receive_start_time',
    )
    lost_lock_time: Optional[str] = Field(
        None,
        description='If the receiver is not currently locked, this is the timestamp when the modem first detected the loss of lock on the carrier.',
        title='lost_lock_time',
    )
    cn0_n0_dB: Optional[float] = Field(
        None,
        description='Carrier + noise divided by noise. An approximation for SNR independent of modulation type.',
        title='cn0_n0_dB',
    )
    eb_n0_dB: Optional[float] = Field(
        None,
        description='Energy per bit to noise power spectral density ratio. Note – for this to be accurate, you must know the modulation type.',
        title='eb_n0_dB',
    )
