# generated by datamodel-codegen:
#   filename:  CSI-002-020_SimpleSdrReceive.yml
#   timestamp: 2023-05-25T22:20:02+00:00

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


class ParametersOutputEnabled(Enum):
    ENABLED_DISABLED = 'ENABLED DISABLED'


class SimpleSdrReceive(BaseModel):
    parameters_antenna_dc_v: Optional[float] = Field(
        None,
        alias='parameters.antenna_dc_v',
        description='Sets or gets the DC voltage on the port that can be used to power an antenna.',
        title='antenna_dc_v',
    )
    parameters_gain_db: Optional[float] = Field(
        None,
        alias='parameters.gain_db',
        description='Gain applied to the port. This gain setting affects all downstream channels.',
        title='gain_db',
    )
    parameters_tune_frequency_hz: Optional[float] = Field(
        None,
        alias='parameters.tune_frequency_hz',
        description='This is the retune frequency used to convert to a baseband channel.',
        title='tune_frequency_hz',
    )
    parameters_sample_rate_hz: Optional[float] = Field(
        None,
        alias='parameters.sample_rate_hz',
        description='This is the sample rate of the baseband channel.',
        title='sample_rate_hz',
    )
    parameters_magnitude_correction_db: Optional[float] = Field(
        None,
        alias='parameters.magnitude_correction_db',
        description='This is used to calibrate each instance of hardware to account for manufacturing differences between units when calculating floating-point I/Q.',
        title='magnitude_correction_db',
    )
    parameters_output_enabled: Optional[ParametersOutputEnabled] = Field(
        None,
        alias='parameters.output_enabled',
        description='ENABLED- The I/Q data is written to the output stream, DISABLED- The hardware is active, but the I/Q data is not written to the output stream.',
        title='output_enabled',
    )
    parameters_output_stream_id: Optional[str] = Field(
        None,
        alias='parameters.output_stream_id',
        description='UUID of the output stream of I/Q samples.',
        title='output_stream_id',
    )
    sensors_rssi_dbm: Optional[float] = Field(
        None,
        alias='sensors.rssi_dbm',
        description='This is the received signal strength indication of the baseband channel.',
        title='rssi_dbm',
    )
