# generated by datamodel-codegen:
#   filename:  CSI-002-021_SimpleSdrTransmit.yml
#   timestamp: 2023-05-25T22:20:26+00:00

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


class ParametersOutputEnabled(Enum):
    ENABLED_DISABLED = 'ENABLED DISABLED'


class SimpleSdrTransmit(BaseModel):
    parameters_output_enabled: Optional[ParametersOutputEnabled] = Field(
        None,
        alias='parameters.output_enabled',
        description='ENABLED- transmit is enabled. DISABLED- Transmit hardware is active, but not transmitting.',
        title='output_enabled',
    )
    parameters_gain_db: Optional[float] = Field(
        None,
        alias='parameters.gain_db',
        description='Gain applied to the I/Q samples.',
        title='gain_db',
    )
    parameters_center_frequency_hz: Optional[float] = Field(
        None,
        alias='parameters.center_frequency_hz',
        description='This is the center frequency used to convert the I/Q baseband to the intermediate frequency output by the SDR Transmit.',
        title='center_frequency_hz',
    )
    parameters_sample_rate_hz: Optional[float] = Field(
        None,
        alias='parameters.sample_rate_hz',
        description='This is the sample rate of the baseband channel.',
        title='sample_rate_hz',
    )
    parameters_input_stream_id: Optional[str] = Field(
        None,
        alias='parameters.input_stream_id',
        description='UUID of the input stream of I/Q samples.',
        title='input_stream_id',
    )
    sensors_measured_power_out_dbm: Optional[float] = Field(
        None,
        alias='sensors.measured_power_out_dbm',
        description='This is the measured output going out the transmit port.',
        title='measured_power_out_dbm',
    )
