# generated by datamodel-codegen:
#   filename:  CSI-004-004_RationalResampler.yml
#   timestamp: 2023-05-25T22:25:39+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class RationalResamplerYml(BaseModel):
    format_version: Optional[str] = Field(
        None,
        description='“rational_resampler-2022.04.18” for this version, which specifies the fields in this table.',
        title='format_version',
    )
    parameters_stream_id_in: Optional[str] = Field(
        None,
        alias='parameters.stream_id_in',
        description='DSP tap stream identifier from which to read input samples.',
        title='stream_id_in',
    )
    parameters_stream_id_out: Optional[str] = Field(
        None,
        alias='parameters.stream_id_out',
        description='DSP tap stream identifier that points to the output of the rational resampler.',
        title='stream_id_out',
    )
    parameters_interpolation: Optional[float] = Field(
        None,
        alias='parameters.interpolation',
        description='Interpolation/upsample factor.',
        title='interpolation',
    )
    parameters_decimation: Optional[float] = Field(
        None,
        alias='parameters.decimation',
        description='Decimation/downsample factor.',
        title='decimation',
    )
    parameters_taps: Optional[str] = Field(
        None, alias='parameters.taps', description='Filter coefficients.', title='taps'
    )
    parameters_fractional_bandwidth: Optional[float] = Field(
        None,
        alias='parameters.fractional_bandwidth',
        description='The absolute bandwidth divided by the center frequency.',
        title='fractional_bandwidth',
    )
