# generated by datamodel-codegen:
#   filename:  CSI-004-001_RawDataCapture.yml
#   timestamp: 2023-05-25T22:24:28+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Optional

from pydantic import BaseModel, Field


class ParametersCapture(Enum):
    START_CAPTURE = 'START_CAPTURE'
    STOP_CAPTURE = 'STOP_CAPTURE'


class ParametersCaptureStatus(Enum):
    IDLE = 'IDLE'
    PRE_BUFFER = 'PRE_BUFFER'
    CAPTURING = 'CAPTURING'


class ParametersSendSnapshots(Enum):
    ENABLED = 'ENABLED'
    DISABLED = 'DISABLED'


class RawDataCaptureYml(BaseModel):
    format_version: Optional[str] = Field(
        None,
        description='“raw_capture-2022.03.26” for this version, which specifies the fields in this table.',
        title='format_version',
    )
    last_snapshot: Optional[Any] = Field(
        None,
        description='Gets an image of the last snapshot taken during raw capture process.',
        title='last_snapshot',
    )
    parameters_prefix_1: Optional[str] = Field(
        None,
        alias='parameters.prefix_1',
        description='Prefix added to file names to provide context for captures',
        title='prefix_1',
    )
    parameters_prefix_2: Optional[str] = Field(
        None,
        alias='parameters.prefix_2',
        description='Prefix added to file names to provide context for captures',
        title='prefix_2',
    )
    parameters_stream_id_monitored: Optional[str] = Field(
        None,
        alias='parameters.stream_id_monitored',
        description='The identifier of the I/Q stream to be monitored.',
        title='stream_id_monitored',
    )
    parameters_pre_trigger_buffer_seconds: Optional[float] = Field(
        None,
        alias='parameters.pre_trigger_buffer_seconds',
        description='The amount of data to capture before the trigger command is received to ensure events of interest that preceded the capture command are stored as well. Set to 0 to disable.',
        title='pre_trigger_buffer_seconds',
    )
    parameters_post_trigger_capture_seconds: Optional[float] = Field(
        None,
        alias='parameters.post_trigger_capture_seconds',
        description='The amount of data to capture after the trigger command is received.',
        title='post_trigger_capture_seconds',
    )
    parameters_capture: Optional[ParametersCapture] = Field(
        None,
        alias='parameters.capture',
        description='start the capture.',
        title='capture',
    )
    parameters_capture_status: Optional[ParametersCaptureStatus] = Field(
        None,
        alias='parameters.capture_status',
        description='Status of the capture process, IDLE- There is no pre-buffer active, and the proxy is not capturing data, PRE_BUFFER- The proxy is capturing only the pre-buffer data, CAPTURING- The proxy is currently filling the post-trigger buffer with raw I/Q data.',
        title='capture_status',
    )
    parameters_send_snapshots: Optional[ParametersSendSnapshots] = Field(
        None,
        alias='parameters.send_snapshots',
        description='Send snapshots to the C2 hub at the interval defined by snapshot_interval_seconds.',
        title='send_snapshots',
    )
    parameters_snapshot_interval_seconds: Optional[float] = Field(
        None,
        alias='parameters.snapshot_interval_seconds',
        description='Delay inserted between capturing a spectrum snapshot image and sending to the C2 Hub.',
        title='snapshot_interval_seconds',
    )
